# Generated by Django 3.2.8 on 2023-05-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_category_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default='a1b11450eb81f2', max_length=11, unique=True),
        ),
    ]
