# Generated by Django 3.2.8 on 2023-05-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default='2d70fe86d8261b', max_length=20, unique=True),
        ),
    ]
