# Generated by Django 3.2.8 on 2023-04-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('psswd', models.CharField(max_length=20)),
                ('block', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
