# Generated by Django 3.2.8 on 2023-04-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='consecutive',
            field=models.CharField(max_length=15),
        ),
    ]
